### ISSUE TITLE
[BUG] Jenkins Localhost 관련 문제 해결

### ISSUE THREAD

**Issue by YoonAh-dev** [TeamHavit/Havit-iOS#20]
# 🐞 버그 설명
| 문제 발생 일시 |  발생 위치  | 발생 조건 |
| :---: | :---: | --- | 
| 2022.01.12  | Github Webhook  |  | 

## 증상 

 localhost때문에 PR마다 CI가 달리지 않는 문제를 해결해야 합니다.

* 도커 컨테이너에 젠킨스를 설치해서 도커에서 젠킨스를 사용하도록 구현할 예정입니다.
* 성공해서 돌아오겠습니다.

**Comment by YoonAh-dev** [comment]
@sujinnaljin @noah0316 @beansbin @Suyeon9911 
도커를 사용하는 방식은 완벽하게 실패했습니다.💩

**[ 문제점 ]**

1. 도커 안에 있는 젠킨스는 Linux 기반의 Built-In Node를 가지고 있습니다.
    ![스크린샷 2022-01-12 오전 5 07 37](https://user-images.githubusercontent.com/55099365/149013585-3bfc365c-f1bc-449d-943a-cf7957e0dc24.png)
   * Havit Test는 `xcode`설치를 기반으로 합니다. 따라서 Linux인 노드에서는 안돌아갑니다. 
   * Xcode install이 안되어 있기 때문에 `xcodebuild`라는 테스트 첫문장을 이해할 수가 없어서 테스트가 fail납니다. 
   * install한다고 해서 Linux가 다운로드 받아줄지도 의문입니다.
   * Mac OS로 Node를 받고 싶었으니 Node Create하는 방법을 도통 모르겠어서 관뒀습니다.
   * 혹시나 젠킨스를 도커에 다운받아보고 싶으시다면 https://soojae.tistory.com/23 를 참고하세요.

2. 제 Webhook에서 Jenkins와 연동이 안되었던 이유가 정적이지 않은 IP때문이었습니다. IP 주소는 제가 연결한 Wifi에 따라서 계속 바뀌기 때문에 제대로 데이터 전달이 안됐던 겁니다.


<br/>
<br/>

**[ 해결 방식 ]**

1. ngrok를 이용해서 논포트포워딩 서버를 만듭니다.
   * `ngrok` : 외부에서 로컬에 접속 가능하게 하는 터널 프로그램
   * Jenkins를 Github WebHook에서 사용하려면 외부 접속이 가능해야합니다.
   * https://json8.tistory.com/139 < 이 방식을 써서 Localhost에서 외부 접속이 가능하게 하는 방식도 있어요. 하지만 불안정합니다. 랜선을 직접 연결하는게 아닌 이상 Wifi를 사용하면 IP주소가 계속 바뀝니다.
   * https://ngrok.com/download < ngrok를 사용해서 외부 접속이 가능하게 만들어줍시다.
      <img width="827" alt="스크린샷 2022-01-12 오전 5 28 15" src="https://user-images.githubusercontent.com/55099365/149016333-684ba371-f0b8-406f-84c5-47784f244007.png">
   
   * 해당 ngrok 다운로드 방식을 따라하면 ngrok이 다운로드되는데 거기서 주는 URL를 넣어주시면 됩니다.
     <img width="460" alt="스크린샷 2022-01-12 오전 5 32 46" src="https://user-images.githubusercontent.com/55099365/149016955-05a8d79c-62c6-4a28-8775-a215a708c12c.png">


<br/>
<br/>

<img width="796" alt="스크린샷 2022-01-12 오전 5 37 28" src="https://user-images.githubusercontent.com/55099365/149017693-e6fbcdd4-b4ae-4f55-b6e7-d6530e7eccf3.png">

redelivery를 통해서 보낸 값이 POST 200뜨는 모습을 보긴했는데 실제로 되는건지는 풀리퀘를 날리면 알 수 있을 것 같고, 혹시 안된다면 그냥 Github Action에다가 넣을 생각입니다. Jenkins가 어렵다. 어렵다. 듣긴했는데, 진짜로 너무 어렵고.. 눈물나고.. 그렇습니다.😢

**Comment by sujinnaljin** [comment]
> Mac OS로 Node를 받고 싶었으니 Node Create하는 방법을 도통 모르겠어서 관뒀습니다. 

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ눈,,물,, 저는 젠킨즈가 빌드 가상환경까지 제공해주는건줄 알았는데 그건 또 아니었나보군여 ㅋㅋㅋㅋ

> Jenkins가 어렵다. 어렵다. 듣긴했는데, 진짜로 너무 어렵고.. 눈물나고.. 그렇습니다.😢

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ쿠ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ ㅇㄴ 사람들 다 어떻게 해왔던거져 정말루~~!! 저도 이따 따로 공부좀 해봐야겠네옄ㅋㅋㅋ 고생하셨어요 대장!

**Comment by Suyeon9911** [comment]
뭔진 모르겠지만... 수고했어요 대장님.. 졌잘싸. 🌿
